name: Build and Upload JAR on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SC_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/my-jar-file.jar
        asset_name: my-jar-file.jar
        asset_content_type: application/java-archive
