name: Upload Docker Image to Repo

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  release:
    types: [published] # Trigger on published releases

jobs:
  load-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Download the Docker image tarball from the release
      - name: Download Docker image tarball
        uses: dawidd6/action-download-release-asset@v2
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          asset_name: starkingdoms.tar

      # Step 3: Load the Docker image from the tarball
      - name: Load Docker image from tarball
        run: |
          docker load < starkingdoms.tar

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Tag the Docker image with the repository name and version
      - name: Tag Docker image
        run: |
          docker tag starkingdoms:latest ${{ secrets.DOCKER_REPO }}/starkingdoms:latest
          docker tag starkingdoms:latest ${{ secrets.DOCKER_REPO }}/starkingdoms:${{ github.run_number }}

      # Step 6: Push the Docker image to the repository
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/starkingdoms:latest
          docker push ${{ secrets.DOCKER_REPO }}/starkingdoms:${{ github.run_number }}
